//Local TOC for river.dita
var TITEMS = [
  ["Рессета — Жиздра", "resseta.html", "11"],
  ["Нерская", "nerskaja.html", "1", 
    ["День 1", "nerskaja1.html", "11"],
    ["День 2", "nerskaja2.html", "11"],
    ["День 3", "nerskaja3.html", "11"]
  ],
  ["Осуга", "osuga_.html", "1", 
    ["Река Осуга", "osuga0.html", "11"],
    ["День 1", "osuga1.html", "11"],
    ["День 2", "osuga2.html", "11"],
    ["День 3", "osuga3.html", "11"],
    ["День 4", "osuga4.html", "11"]
  ],
  ["Калга — Белое море", "calga_.html", "1", 
    ["Немного видео", "calga_video.html", "11"],
    ["День 1", "calga1.html", "11"],
    ["День 2", "calga2.html", "11"],
    ["День 3", "calga3.html", "11"],
    ["День 4", "calga4.html", "11"],
    ["День 5", "calga5.html", "11"],
    ["День 6", "calga6.html", "11"],
    ["День 7", "calga7.html", "11"],
    ["День 8", "calga8.html", "11"],
    ["День 9", "calga9.html", "11"],
    ["День 10", "calga10.html", "11"],
    ["День 11", "calga11.html", "11"],
    ["День 12-13", "calga12.html", "11"],
    ["День 14", "calga14.html", "11"]
  ],
  ["Рессета — Жиздра", "resseta09.html", "11"],
  ["Поведь", "poved.html", "1", 
    ["Как это было", "poved1.html", "11"]
  ],
  ["Винча — Белое море", "vincha.html", "1", 
    ["День 1", "vincha1.html", "11"],
    ["День 2", "vincha2.html", "11"],
    ["День 3", "vincha3.html", "11"],
    ["День 4", "vincha4.html", "11"],
    ["День 5", "vincha5.html", "11"],
    ["День 6", "vincha6.html", "11"],
    ["День 7", "vincha7.html", "11"],
    ["День 8", "vincha8.html", "11"],
    ["День 9", "vincha9.html", "11"],
    ["День 10", "vincha10.html", "11"],
    ["День 11", "vincha11.html", "11"],
    ["День 12", "vincha12.html", "11"],
    ["День 13", "vincha13.html", "11"],
    ["День 14", "vincha14.html", "11"],
    ["День 15", "vincha15.html", "11"]
  ],
  ["Киржач", "kirzhach09.html", "11"],
  ["Щегринка", "shegrinka.html", "11"],
  ["Корёжечная", "koprozhechna.html", "11"],
  ["Граничная", "granichnaja.html", "1", 
    ["Как это было", "granichnaja1.html", "11"]
  ],
  ["Вуокса", "vuoksa.html", "11"],
  ["Белое море 2010", "whitesea2010.html", "1", 
    ["Статистика", "whitesea2010.stat.html", "11"],
    ["Фотографии", "whitesea2010.photo.html", "11"]
  ],
  ["Тудовка — Волга", "tutovka.html", "11"],
  ["Лопасня — Ока", "lopasna.html", "11"],
  ["Полометь", "polomet.html", "11"],
  ["Вуокса 2012", "vuoksa2012.html", "11"],
  ["Поля", "pola2012.html", "11"],
  ["Созь", "sozz.html", "11"],
  ["Шаня", "shana.html", "11"],
  ["Московское море", "mossea14.html", "11"],
  ["Онежское озеро", "onega.html", "11"],
  ["Ладожское озеро", "ladoga.html", "11"],
  ["Ладога (план)", "ladoga14.html", "11"]
];